### PR TITLE
Add forms

### PR DESCRIPTION
**Pull request by butlermuwo**
## Forms
In this pull request I did the following:
- Created a Post on behalf of the current_user.
- Created a comment on behalf of the current_user.
- Created a provision to allow Users to add likes to Posts.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
### Hi @butlermuwo  
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Your code organization is good.
 
 ## Required Changes 
 - [ ] Please update your database in `database.yml` file because I am getting an error.
Screenshot from 2022-05-12 23-14-48
- [ ] _Check inline comments for more info_

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by butlermuwo** [comment]
Hey, @GzimAsani Everything is working perfectly fine on my end.

**Comment by butlermuwo** [comment]
Check reference here: @GzimAsani 
Screenshot (105)

**Comment by GzimAsani** [comment]
> Check reference here: @GzimAsani
> Screenshot (105)

Please ask for another code review. It was showing an error on my  end when I tried it

**Review by rukundoeric — APPROVED** [review]
Hi @butlermuwo,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by butlermuwo** [comment]
Thanks @rukundoeric & @GzimAsani

**Pull request merged**
